<?php

// php / 的结果是浮点数，要用floor舍去法才能到商。

function ex1(){	
  // Add all the natural numbers below one thousand that are multiples of 3 or 5.
  // 自然数1000以下的由3和5乘得。（答案:233168）
  // 第一种解法，很自然想到整除
  $a=0;
  for ($i=0;$i<1000;$i++){
    if (( $i % 3 == 0 ) or ( $i % 5 == 0 )){
       $a += $i;
    }
  }
  echo $a;
  echo "\n";
  // 第二种解法，观察3,6,9,12,15....998,999 相当于(1+2+3+4+5+...+333)X3
  // 观察5,10,15,20,25 相当于(1+2+3+4+5+...+198+199)X5,凡是15的倍数就被重复了。
  // 求和3 求和5，然后再减去15
  
  function c3($num){
    $b=999;
    $p = floor($b / $num);
    $x=(1+$p)*$p/2*$num;
    return $x;
  }
  echo c3(3)+c3(5)-c3(15);
}   


function ex2(){
  // Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  // Find the sum of all the even-valued terms in the sequence which do not exceed four million.  // Find the sum of all the even-valued terms in the Fibonacci sequence which do not exceed four million.
  // 求费波拉数列中不超过4百万的所有偶数
  // 观察后发现有规律，用%2的方法判断偶数是很蠢的。如果前面多补一个1，那么每间隔两个奇数就会出现一个是偶数！
  $limit=4000000;
  $sum=0;
  $a=1;
  $b=1;
  $c=$a+$b;
  while ($c<$limit){
    $sum+=$c;
    $a=$b+$c;
    $b=$c+$a;
    $c=$a+$b;
  }
  echo $sum;
}

ex2();

?>
